---
- name: Download Atlantis binary
  shell: wget {{ atlantis_url }}

- name: Extract Atlantis
  shell: sudo unzip atlantis_linux_amd64.zip -d /usr/local/bin/

- name: Install Ansible
  shell: sudo apt -y install ansible

- name: Install Terraform
  shell: sudo apt-get install terraform

- name: Install AWS boto3
  shell: pip install boto3

- name: Install Infracost
  shell: curl -fsSL {{ infracost_url }} |sudo sh

- name: Install terragrunt-atlantis-config
  shell: sudo install terragrunt-atlantis-config /usr/local/bin

- name: Install Terragrunt
  shell: sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt && chmod +x /usr/local/bin/terragrunt

- name: Install terragrunt-atlantis-config
  shell: sudo install terragrunt-atlantis-config /usr/local/bin