---
plugin: aws_ec2

regions:
  - us-east-1

keyed_groups:
  - key: tags.Name
    separator: ""
    #    prefix: tag
    #  - prefix: instance_type
    #    key: instance_type
    #  - key: placement.region
    #    prefix: aws_region

filters:
  instance-state-name : running
